import type { Ability, FragmentItem, Plot, Weapon } from "@/lib/sheet-types";

export type CatalogCategory = "trama" | "transcendente" | "fragmento" | "arma";

export interface CatalogEntry {
  id: string;
  category: CatalogCategory;
  name: string;
  subtitle: string;
  summary: string;
  tags: string[];
  payload: Plot | Ability | FragmentItem | Weapon;
}

const plot = (
  id: string,
  name: string,
  subtitle: string,
  summary: string,
  resistance: string,
  tags: string[],
): CatalogEntry => ({
  id,
  category: "trama",
  name,
  subtitle,
  summary,
  tags,
  payload: {
    id,
    nome: name,
    uso: subtitle.split(" · ")[2] ?? "",
    alcance: subtitle.split(" · ")[3] ?? "",
    dano: "",
    efeito: summary,
    dt_descricao: resistance,
  },
});

const ability = (
  id: string,
  name: string,
  branch: string,
  summary: string,
  price: string,
): CatalogEntry => ({
  id,
  category: "transcendente",
  name,
  subtitle: branch,
  summary,
  tags: [branch, "Concedida pela história"],
  payload: { id, nome: name, descricao: summary, modificador: price },
});

export const RULEBOOK_CATALOG: CatalogEntry[] = [
  plot(
    "catalog-plot-sutura",
    "Sutura Breve",
    "Medo · Eclis · Repuxo · Toque",
    "Recupera 1d6 PV e interrompe Sangrando; deixa uma cicatriz incomum.",
    "Medicina ou Fortitude, se houver resistência",
    ["Medo", "Eclis", "Repuxo", "Cura"],
  ),
  plot(
    "catalog-plot-peso",
    "Peso da Carne",
    "Medo · Eclis · Tração · Próximo",
    "Reduz o deslocamento à metade e impede reação de movimento por uma rodada.",
    "Fortitude",
    ["Medo", "Eclis", "Tração", "Controle"],
  ),
  plot(
    "catalog-plot-quarto",
    "Quarto Sem Saída",
    "Medo · Thyren · Tração · Cena",
    "Oculta uma passagem de quem não presenciou a Costura.",
    "Percepção ou Temperança",
    ["Medo", "Thyren", "Tração", "Ocultação"],
  ),
  plot(
    "catalog-plot-sentenca",
    "Sentença Gravada",
    "Medo · Zha’el · Estiramento · Toque",
    "Vincula uma declaração aceita a uma consequência definida.",
    "Convicção",
    ["Medo", "Zha’el", "Estiramento", "Vínculo"],
  ),
  plot(
    "catalog-plot-lembranca",
    "Lembrança de Superfície",
    "Conhecimento · Memória · Repuxo · Toque",
    "Revela uma impressão sensorial breve do último evento significativo de um objeto.",
    "Sem resistência",
    ["Conhecimento", "Memória", "Repuxo", "Investigação"],
  ),
  plot(
    "catalog-plot-nome",
    "Nome Exato",
    "Conhecimento · Linguagem · Tração · Próximo",
    "Enfraquece disfarces e ocultações enquanto o nome correto for sustentado.",
    "Temperança",
    ["Conhecimento", "Linguagem", "Tração", "Revelação"],
  ),
  plot(
    "catalog-plot-simbolo",
    "Peso do Símbolo",
    "Conhecimento · Significância · Tração · Próximo",
    "Concede +1d20 a quem age de acordo com o sentido atribuído ao objeto.",
    "Convicção",
    ["Conhecimento", "Significância", "Tração", "Apoio"],
  ),
  plot(
    "catalog-plot-retorno",
    "Fio de Retorno",
    "Conhecimento · Alma · Estiramento · Cena",
    "Liga dois Vínculos para compartilharem PA e perceberem a direção um do outro.",
    "Convicção",
    ["Conhecimento", "Alma", "Estiramento", "Vínculo"],
  ),
  plot(
    "catalog-plot-instante",
    "Instante Repetido",
    "Tempo · Fluxo · Tração · Próximo",
    "Repete uma ação simples recém-concluída com uma nova resolução.",
    "Temperança ou Reflexo",
    ["Tempo", "Fluxo", "Tração", "Repetição"],
  ),
  plot(
    "catalog-plot-atraso",
    "Atraso Verde",
    "Tempo · Fluxo · Repuxo · Próximo",
    "Adia dano ou condição até o fim do próximo turno.",
    "Concentração",
    ["Tempo", "Fluxo", "Repuxo", "Adiamento"],
  ),
  plot(
    "catalog-plot-janela",
    "Janela Anterior",
    "Tempo · Fluxo · Estiramento · Cena",
    "Sobrepõe por uma rodada uma configuração passada do local.",
    "Sem resistência",
    ["Tempo", "Fluxo", "Estiramento", "Cena"],
  ),
  plot(
    "catalog-plot-silencio",
    "Silêncio de Costura",
    "Conhecimento · Linguagem/Thyren · Repuxo · Próximo",
    "Impede que sons atravessem uma borda escolhida enquanto sustentada.",
    "Concentração",
    ["Conhecimento", "Repuxo", "Silêncio"],
  ),
  ability(
    "catalog-trans-limiar",
    "Limiar da Carne",
    "Corpóreo",
    "Mantém a personagem ativa temporariamente ao chegar a 0 PV.",
    "Preço: recebe uma Marca adicional ao final.",
  ),
  ability(
    "catalog-trans-arquitetura",
    "Arquitetura do Instinto",
    "Corpóreo",
    "Uma vez por cena, permite agir antes de todos; ações defensivas recebem +2d20.",
    "Preço: fica Abalado depois.",
  ),
  ability(
    "catalog-trans-inverso",
    "Carne do Inverso",
    "Corpóreo",
    "Presenças simples de Eclis hesitam antes de atacar e enfrentam Temperança DT 15.",
    "Preço: Tramas de Conhecimento contra a personagem recebem +1 DT.",
  ),
  ability(
    "catalog-trans-olho",
    "Olho que Não Fecha",
    "Cônscio",
    "Uma vez por cena, revela uma verdade passada de um objeto ou lugar.",
    "Preço: perde 1 PS que não retorna por descanso comum.",
  ),
  ability(
    "catalog-trans-gramatica",
    "Gramática do Véu",
    "Cônscio",
    "Selagens lideradas recebem -3 DT e falha simples não causa Refluxo Severo.",
    "Preço: cada Selagem deixa um símbolo ou frase recorrente.",
  ),
  ability(
    "catalog-trans-arquivo",
    "Voz do Arquivo",
    "Cônscio",
    "Uma vez por sessão, obtém da Chama Fria uma resposta verdadeira, mas incompleta.",
    "Preço: 3 PS e 1 Tensão de Conhecimento.",
  ),
  ability(
    "catalog-trans-cicatriz",
    "Cicatriz do Fluxo",
    "Canalizado",
    "Converte a consequência principal de Refluxo em dano de PS escalonado.",
    "Preço: recebe Descompassado.",
  ),
  ability(
    "catalog-trans-tecelao",
    "Tecelão",
    "Canalizado",
    "Combina duas Naturezas usando a maior DT +3 e o maior custo +1.",
    "Preço: uma falha produz Refluxo de ambas.",
  ),
  ability(
    "catalog-trans-espelho",
    "Espelho do Além",
    "Canalizado",
    "Uma vez por sessão, ignora por uma cena efeitos ambientais passivos de Dobras.",
    "Preço: Pulsos ainda afetam diretamente.",
  ),
  ability(
    "catalog-trans-concordancia",
    "Concordância Impossível",
    "Cinético",
    "Uma vez por cena, trata um teste social como 20 natural sem crítico automático.",
    "Preço: o acordo cria uma expectativa futura.",
  ),
  ability(
    "catalog-trans-passo",
    "Passo Entre",
    "Cinético",
    "Uma vez por combate, fica Oculto como Ação Livre até agir.",
    "Preço: recebe 1 Tensão ligada à Dobra local.",
  ),
  ability(
    "catalog-trans-ancora",
    "Âncora Humana",
    "Cinético",
    "Uma vez por sessão, protege um aliado de Tensão forçada e condições mentais por uma cena.",
    "Preço: termina se os PS da personagem caírem à metade.",
  ),
  ...[
    ["I", "3", "Repuxo"],
    ["II", "6", "Tração"],
    ["III", "10", "Estiramento"],
  ].map(([category, integrity, limit]): CatalogEntry => ({
    id: `catalog-fragment-${category}`,
    category: "fragmento",
    name: `Fragmento Categoria ${category}`,
    subtitle: `Integridade ${integrity} · limite ${limit}`,
    summary:
      "Modelo seguro para registrar Natureza, Domínio, Assinatura, Selo e sinais próprios.",
    tags: ["Fragmento", `Categoria ${category}`, limit],
    payload: {
      id: `catalog-fragment-${category}`,
      nome: `Fragmento Categoria ${category}`,
      descricao: "",
      espaco: 1,
      categoria: category as "I" | "II" | "III",
      integridade: Number(integrity),
      limiteSeguro: limit as "Repuxo" | "Tração" | "Estiramento",
      selo: "Selado",
    },
  })),
  ...[
    ["Leve", "1d6", "20", "Ágil, Ocultável", "1"],
    ["Média", "1d8", "20", "Versátil", "2"],
    ["Pesada", "1d10", "20", "Pesada, Demolidora", "3"],
    ["Excepcional", "1d12", "19", "Duas mãos, Especial", "4"],
    ["Improvisada", "1d4", "19", "Frágil ou Incômoda", "1"],
  ].map(([name, damage, threat, properties, space]): CatalogEntry => ({
    id: `catalog-weapon-${name.toLowerCase()}`,
    category: "arma",
    name: `Arma ${name}`,
    subtitle: `${damage} · ameaça ${threat} · espaço ${space}`,
    summary: `Perfil de arma corpo a corpo ${name.toLowerCase()}.`,
    tags: ["Contato", name, properties],
    payload: {
      id: `catalog-weapon-${name.toLowerCase()}`,
      nome: `Arma ${name}`,
      familia: name === "Improvisada" ? "Improvisada" : "Contato",
      categoria: name,
      dano: damage,
      tipo: "Definir",
      margemAmeaca: threat,
      alcance: "Engajado",
      propriedades: properties,
      espaco: Number(space),
      critico: `×2 (${threat})`,
      peso: Number(space),
      extra: properties,
    },
  })),
];
