/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MasterPanelRouteImport } from './routes/master-panel'
import { Route as ManageUsersRouteImport } from './routes/manage-users'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SheetIdRouteImport } from './routes/sheet.$id'
import { Route as SheetIdPowerRouteImport } from './routes/sheet.$id_.power'

const MasterPanelRoute = MasterPanelRouteImport.update({
  id: '/master-panel',
  path: '/master-panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetIdRoute = SheetIdRouteImport.update({
  id: '/sheet/$id',
  path: '/sheet/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetIdPowerRoute = SheetIdPowerRouteImport.update({
  id: '/sheet/$id_/power',
  path: '/sheet/$id/power',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manage-users': typeof ManageUsersRoute
  '/master-panel': typeof MasterPanelRoute
  '/sheet/$id': typeof SheetIdRoute
  '/sheet/$id/power': typeof SheetIdPowerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manage-users': typeof ManageUsersRoute
  '/master-panel': typeof MasterPanelRoute
  '/sheet/$id': typeof SheetIdRoute
  '/sheet/$id/power': typeof SheetIdPowerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/manage-users': typeof ManageUsersRoute
  '/master-panel': typeof MasterPanelRoute
  '/sheet/$id': typeof SheetIdRoute
  '/sheet/$id_/power': typeof SheetIdPowerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/manage-users'
    | '/master-panel'
    | '/sheet/$id'
    | '/sheet/$id/power'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/manage-users'
    | '/master-panel'
    | '/sheet/$id'
    | '/sheet/$id/power'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/manage-users'
    | '/master-panel'
    | '/sheet/$id'
    | '/sheet/$id_/power'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  ManageUsersRoute: typeof ManageUsersRoute
  MasterPanelRoute: typeof MasterPanelRoute
  SheetIdRoute: typeof SheetIdRoute
  SheetIdPowerRoute: typeof SheetIdPowerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/master-panel': {
      id: '/master-panel'
      path: '/master-panel'
      fullPath: '/master-panel'
      preLoaderRoute: typeof MasterPanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage-users': {
      id: '/manage-users'
      path: '/manage-users'
      fullPath: '/manage-users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$id': {
      id: '/sheet/$id'
      path: '/sheet/$id'
      fullPath: '/sheet/$id'
      preLoaderRoute: typeof SheetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet/$id_/power': {
      id: '/sheet/$id_/power'
      path: '/sheet/$id/power'
      fullPath: '/sheet/$id/power'
      preLoaderRoute: typeof SheetIdPowerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  ManageUsersRoute: ManageUsersRoute,
  MasterPanelRoute: MasterPanelRoute,
  SheetIdRoute: SheetIdRoute,
  SheetIdPowerRoute: SheetIdPowerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
