// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { RuntimeDatabase } from "./database-runtime-types";
import { resolvePublicSupabaseConfig } from "./public-config";

function createSupabaseClient() {
  const runtimeEnvironment =
    typeof process !== "undefined"
      ? {
          SUPABASE_PROJECT_ID: process.env.SUPABASE_PROJECT_ID,
          SUPABASE_URL: process.env.SUPABASE_URL,
          SUPABASE_PUBLISHABLE_KEY: process.env.SUPABASE_PUBLISHABLE_KEY,
        }
      : {};
  const { url, publishableKey } = resolvePublicSupabaseConfig({
    ...runtimeEnvironment,
    VITE_SUPABASE_PROJECT_ID: import.meta.env.VITE_SUPABASE_PROJECT_ID,
    VITE_SUPABASE_URL: import.meta.env.VITE_SUPABASE_URL,
    VITE_SUPABASE_PUBLISHABLE_KEY: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
  });

  return createClient<RuntimeDatabase>(url, publishableKey, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
